logging:
    level:
        org:
            springframework:
                web: DEBUG
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        initialization: always
        password: aefdaf5763759fbbb5a426ba760f5288b4e74808053cbb28db14075fcb6a79b7
        testWhileIdle: true
        url: jdbc:postgresql://ec2-3-231-69-204.compute-1.amazonaws.com:5432/da6rbtn5phqvkk
        username: sukiqvzolsbbpu
        validationQuery: SELECT 1
    jpa:
        generate-ddl: true
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 97330989195-eeb5iqmomfu7k03ghiqbcijne16koj66.apps.googleusercontent.com
                        client-secret: PeMsyaD8I-w1W2t9kPpjBwv5
                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                          - email
                          - profile
