logging:
    level:
        org:
            springframework:
                web: DEBUG
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        initialization: always
        password: '*Sm^XeNqcjBh'
        testWhileIdle: true
        url: jdbc:postgresql://isprojectionfinal.cbzcyx28iudw.us-east-2.rds.amazonaws.com:5432/ProjectionRoot
        username: ISMain
        validationQuery: SELECT 1
        maxActive: 5
        minActive: 1
    jpa:
        generate-ddl: true
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 97330989195-eeb5iqmomfu7k03ghiqbcijne16koj66.apps.googleusercontent.com
                        client-secret: PeMsyaD8I-w1W2t9kPpjBwv5
                        redirectUri: "https://api.cs.mrg.com.pe/api-sec02-group03/oauth2/callback/{registrationId}"
                        scope:
                          - email
                          - profile
